### ISSUE TITLE
License Specification

### ISSUE THREAD

**Issue by SebStange** [nipanimaju/coming-soon#1]
Hello Pawel,

Can you please specify the exact CC license you've published this under?

For example [CC0](https://creativecommons.org/publicdomain/zero/1.0/) or [CC BY](https://creativecommons.org/licenses/by/4.0/)?

**Comment by nipanimaju** [comment]
Hi, I mean CC by :)

wt., 3 lis 2020, 18:26 użytkownik Sebastian Stange <notifications@github.com>
napisał:
